---
title: "Open Science Software in Developing Countries"
subtitle: "Download Data Analysis of CRAN R Packages"
author: "Han-Wu-Shuang Bao"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float:
      collapsed: false
      smooth_scroll: false
    code_download: false
    anchor_sections: true
    # df_print: kable
    highlight: pygments
---

```{=html}
<style type="text/css">
  body { font-family: "Source Sans Pro", "Arial", sans-serif;
         font-size: 14px; color: #000; }
  code { font-family: "Maple Mono SC NF", "Consolas", monospace; }
  pre code span.do { font-style: normal; font-weight: bold; }
  pre code span.co { font-style: normal; color: #999; }
  pre code span.fu { color: #8959a8; }
  #header { text-align: center; }
  h1, h2, h3 { font-weight: bold; }
  h1.title { font-size: 34px; }
  h1 { font-size: 32px; }
  h2 { font-size: 28px; }
  h3 { font-size: 24px; }
  h4 { font-size: 20px; }
  #TOC li { font-size: 18px; line-height: 1.25; }
  p, li, button span { font-size: 16px; }
  .table { table-layout: fixed; width: auto; margin: 1em auto; }
  .table { border-top: 1px solid #111; border-bottom: 1px solid #111; }
  .table thead { background-color: #f0f0f0; }
  .table tr.even { background-color: #f5f5f5; }
  .table thead tr th { border-bottom-width: 0px; line-height: 1.2; }
  .table tbody tr td { border-top-width: 0px; line-height: 1.2; }
</style>
```

```{r Config, include=FALSE}
options(
  knitr.kable.NA = "",
  digits = 4
)
knitr::opts_chunk$set(
  # collapse = TRUE,
  comment = "",
  fig.width = 8,
  fig.height = 6,
  dpi = 500
)
```

------------------------------------------------------------------------

# Setup

```{r Setup, message=FALSE, warning=FALSE}
## Load R packages

# Core ----
library(cranlogs)
library(jsonlite)

# General ----
library(bruceR)
library(tidyverse)

# Specific ----
library(treemapify)
library(showtext)
library(knitr)
```

# R Package Metadata

```{r Import}
data = import("data.RData")

maintainer = import("CRAN_maintainer.xlsx") %>%
  mutate(across(China:Africa, ~ ifelse(!is.na(.x), cur_column(), NA))) %>%
  unite(region, China:Africa, na.rm=TRUE) %>%
  mutate(region = factor(
    region,
    levels=c("China", "SouthAsia", "WestAsia",
             "SoutheastAsia", "LatinAmerica", "Africa"),
    labels=c("10.4%\n            China",
             "1.7%\n       South\nAsia",
             "0.6%\n     West\nAsia",
             "0.4%\n   Southeast\nAsia",
             "1.6%\n  Latin\n  America",
             "0.3%\n         Africa"))) %>%
  as.data.table() %>%
  unique(by="maintainer")

data = left_join(
  data[, .(pkg, date.init, maintainer)],
  maintainer[, .(maintainer, name, region)],
  by = "maintainer"
)

data[, .(N=.N, Perc=round(100*.N/nrow(data), 1)), keyby=region]

d = data[!is.na(region)]
d.hadley = data[name=="Hadley Wickham"]
```

# CRAN Download Data

The package download count data were retrieved using the [cranlogs](https://cranlogs.r-pkg.org/) package. The raw download logs data were provided by the [RStudio CRAN mirror](http://cran-logs.rstudio.com/). The earliest date available is 2012-10-01.

```{r CRAN Downloads, eval=FALSE}
dd = rbind(d, d.hadley)
N.all.1 = cran_downloads(from="2012-10-01", to="2018-09-30")
N.all.2 = cran_downloads(from="2018-10-01", to="last-day")
N.all = rbind(N.all.1, N.all.2)
N.pkg = do.call(rbind, lapply(1:ceiling(nrow(dd)/200), function(k) {
  id.min = (k - 1) * 200 + 1
  id.max = min(k * 200, nrow(dd))
  fromJSON(paste0(
    "https://cranlogs.r-pkg.org/downloads/total/2012-10-01:",
    Sys.Date(), "/",
    paste(dd$pkg[id.min:id.max], collapse=",")
  ))
}))  # 6 mins

save(N.all, N.pkg, file="downloads.RData")
```

# Data Processing

```{r Merge, warning=FALSE}
load("downloads.RData")

d = left_join(d, N.pkg[c("package", "downloads")],
              by = c("pkg"="package"))
d = add(d, {
  days = as.IDate("2023-10-28") - date.init
  daily.downloads = downloads / days
})

dm = d[order(region, name, -downloads), .(
  downloads = sum(downloads),
  daily.downloads = sum(downloads) / sum(days),
  n.pkgs = .N,
  pkgs = paste(pkg, collapse=", ")
), keyby = .(region, name)][
  order(region, -n.pkgs, -downloads, name)
]

d.hadley = left_join(d.hadley, N.pkg[c("package", "downloads")],
                     by = c("pkg"="package"))

nrow(d)
nrow(dm)
nrow(d.hadley)
round(100 * sum(d$downloads) / sum(N.all$count), 1)
round(100 * sum(d.hadley$downloads) / sum(N.all$count), 1)
```

# Data Visualization

```{r Treemap, fig.width=9, fig.height=7, dpi=500}
dp = copy(dm)
dp[, name.label := ifelse(n.pkgs>=3, name, "") %>%
     str_remove_all("\\d") %>%
     str_trim() %>%
     str_replace_all(" ", "\n") %>%
     str_replace("Yihui\nXie", "Yihui Xie") %>%
     str_replace("Han-Wu-Shuang\nBao", "Han-Wu-\nShuang\nBao") %>%
     str_replace("El\nFodil", "El Fodil") %>%
     str_replace("Dibaba\nBayisa", "Dibaba Bayisa") %>%
     str_replace("Ivan\nJacob\nAgaloos\nPesigan", "Ivan Jacob\nAgaloos Pesigan")]
dp[, sort.downloads := ifelse(n.pkgs>=3, daily.downloads, 0)]
dp = dp[order(region, -n.pkgs, -sort.downloads, name)]

# font_add_google(family="font", name="Roboto Condensed")
font_add(family="font",
         regular="HelveticaNeueLTPro-Cn.otf",
         italic="HelveticaNeueLTPro-CnO.otf",
         bold="HelveticaNeueLTPro-BdCn.otf",
         bolditalic="HelveticaNeueLTPro-BdCnO.otf")
showtext_auto()

# windowsFonts(font=windowsFont("Roboto Condensed"))

p = ggplot(dp, aes(subgroup=region,
                   fill=region,
                   label=name.label,
                   area=n.pkgs)) +
  geom_treemap(aes(alpha=log(daily.downloads)), start="topleft", color="white", show.legend=FALSE) +
  geom_treemap_text(start="topleft", place="center", grow=TRUE,
                    min.size=1, family="font", lineheight=0.16) +
  geom_treemap_subgroup_border(start="topleft", color="white", show.legend=FALSE) +
  geom_treemap_subgroup_text(start="topleft", place="bottomright", grow=TRUE, alpha=0.7,
                             color="white", fontface="bold.italic",
                             min.size=1, family="font", lineheight=0.15) +
  scale_fill_manual(values=c(
    # #647687
    "#ff7f00",  # china
    "#4daf4a",  # south asia
    "#377eb8",  # west asia
    "#e41a1c",  # southeast asia
    "#984ea3",  # latin america
    "#a65628"   # africa
  )) +
  labs(title="R Packages Contributed by People from Developing Countries",
       subtitle=paste0(
         "(",
         round(100 * nrow(dm) / length(unique(maintainer$name))),
         "% of all developers, ",
         round(100 * nrow(d) / nrow(data)),
         "% of all packages, ",
         round(100 * sum(d$downloads) / sum(N.all$count)),
         "% of total downloads)")) +
  theme(plot.title=element_text(family="font", size=90, hjust=0.5),
        plot.subtitle=element_text(family="font", size=60, hjust=0.5))
ggsave(p, file="Fig.CRAN.pkgs.png", width=9, height=7, dpi=500)
```
